/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyUsageResponse { 'date' : string, 'count' : bigint }
export type SubscriptionTier = { 'pro' : null } |
  { 'free' : null };
export type UTRStatus = { 'pending' : null } |
  { 'approved' : null };
export interface UTRSubmission {
  'status' : UTRStatus,
  'principal' : Principal,
  'submittedAt' : bigint,
  'email' : string,
  'utrId' : string,
}
export type UTRVerificationStatus = { 'notSubmitted' : null } |
  { 'pending' : null } |
  { 'approved' : null };
export interface UserProfile {
  'name' : string,
  'lastUsedDate' : string,
  'dailyUsesCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveUTR' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'countSubscribers' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyUsage' : ActorMethod<[], [] | [[UserProfile, DailyUsageResponse]]>,
  'getIsPro' : ActorMethod<[], boolean>,
  'getMyVerificationStatus' : ActorMethod<[], UTRVerificationStatus>,
  'getPendingVerifications' : ActorMethod<[], Array<UTRSubmission>>,
  'getSubscription' : ActorMethod<[], SubscriptionTier>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubscription' : ActorMethod<[Principal], SubscriptionTier>,
  'incrementDailyUsage' : ActorMethod<[string], DailyUsageResponse>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isProCaller' : ActorMethod<[], boolean>,
  'isProUser' : ActorMethod<[Principal], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitUTR' : ActorMethod<[string, string], undefined>,
  'subscribe' : ActorMethod<[SubscriptionTier], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];