/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'lastUsedDate' : IDL.Text,
  'dailyUsesCount' : IDL.Nat,
});
export const DailyUsageResponse = IDL.Record({
  'date' : IDL.Text,
  'count' : IDL.Nat,
});
export const UTRVerificationStatus = IDL.Variant({
  'notSubmitted' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const UTRStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const UTRSubmission = IDL.Record({
  'status' : UTRStatus,
  'principal' : IDL.Principal,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'utrId' : IDL.Text,
});
export const SubscriptionTier = IDL.Variant({
  'pro' : IDL.Null,
  'free' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveUTR' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'countSubscribers' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyUsage' : IDL.Func(
      [],
      [IDL.Opt(IDL.Tuple(UserProfile, DailyUsageResponse))],
      ['query'],
    ),
  'getIsPro' : IDL.Func([], [IDL.Bool], ['query']),
  'getMyVerificationStatus' : IDL.Func([], [UTRVerificationStatus], ['query']),
  'getPendingVerifications' : IDL.Func([], [IDL.Vec(UTRSubmission)], ['query']),
  'getSubscription' : IDL.Func([], [SubscriptionTier], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubscription' : IDL.Func(
      [IDL.Principal],
      [SubscriptionTier],
      ['query'],
    ),
  'incrementDailyUsage' : IDL.Func([IDL.Text], [DailyUsageResponse], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isProCaller' : IDL.Func([], [IDL.Bool], ['query']),
  'isProUser' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitUTR' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'subscribe' : IDL.Func([SubscriptionTier], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'lastUsedDate' : IDL.Text,
    'dailyUsesCount' : IDL.Nat,
  });
  const DailyUsageResponse = IDL.Record({
    'date' : IDL.Text,
    'count' : IDL.Nat,
  });
  const UTRVerificationStatus = IDL.Variant({
    'notSubmitted' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const UTRStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const UTRSubmission = IDL.Record({
    'status' : UTRStatus,
    'principal' : IDL.Principal,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'utrId' : IDL.Text,
  });
  const SubscriptionTier = IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveUTR' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'countSubscribers' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyUsage' : IDL.Func(
        [],
        [IDL.Opt(IDL.Tuple(UserProfile, DailyUsageResponse))],
        ['query'],
      ),
    'getIsPro' : IDL.Func([], [IDL.Bool], ['query']),
    'getMyVerificationStatus' : IDL.Func(
        [],
        [UTRVerificationStatus],
        ['query'],
      ),
    'getPendingVerifications' : IDL.Func(
        [],
        [IDL.Vec(UTRSubmission)],
        ['query'],
      ),
    'getSubscription' : IDL.Func([], [SubscriptionTier], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubscription' : IDL.Func(
        [IDL.Principal],
        [SubscriptionTier],
        ['query'],
      ),
    'incrementDailyUsage' : IDL.Func([IDL.Text], [DailyUsageResponse], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isProCaller' : IDL.Func([], [IDL.Bool], ['query']),
    'isProUser' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitUTR' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'subscribe' : IDL.Func([SubscriptionTier], [], []),
  });
};

export const init = ({ IDL }) => { return []; };